FROM mysql:latest                                                                                                               
                                                                                                                                      
RUN mkdir -p /data/
ENV datadir=/var/lib/mysql                                                                                           
#ENV PGLOG=/data/log/
ENV MYSQL_ROOT_PASSWORD=123456
ENV MYSQL_DATABASE=db_test
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=123456
