FROM postgres:9.5                                                                                                                   
                                                                                                                                      
RUN mkdir -p /data/
ENV PGDATA=/data/main                                                                                                 
ENV PGLOG=/data/log/
ENV POSTGRES_PASSWORD=987456
